# Spring Framework and common settings
server:
  port: ${PORT:8080}

spring:
  profiles:
    active: test
  data:
    mongodb:
      uri: mongodb+srv://octopus:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Telegram API settings
telegram:
  token: 999999999:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  username: OctoshellBot

  use-proxy: false
  proxy:
    host: zhum-eu.freeddns.org
    port: 9000
    type: SOCKS5 # possible values: NO_PROXY, HTTP, SOCKS4, SOCKS5

    use-auth: true
    auth:
      user: XXXX
      password: XXXXXXXXXXXXXXXXXX

# VKontakte API settings
vk:
  group-id: 999999999
  access-token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  confirmation-code: xxxxxxxx

# Octoshell main app settings
remote:
  url: http://localhost:5000/core/bot_links_api