spring:
  profiles:
    active: test
  data:
    mongodb:
      uri: mongodb+srv://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

bot:
  token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  username: OctoshellBot

  use-proxy: true
  proxy:
    host: zhum-eu.freeddns.org
    port: 9000
    type: SOCKS5 # possible values: NO_PROXY, HTTP, SOCKS4, SOCKS5

    use-auth: true
    auth:
      user: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

remote:
  url: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX